# Generated by Django 4.0.6 on 2022-07-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Entry Price')),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Take Profit')),
                ('shares', models.IntegerField(verbose_name='Number of Shares')),
                ('locate_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Locate Fees')),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Exit Price')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Commission')),
                ('wl', models.CharField(max_length=2, verbose_name='W/L')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Profit')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Screenshot')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
            ],
        ),
    ]
