# Generated by Django 4.0.6 on 2022-07-25 06:16

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_equity', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Initial Equity')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Equity at Time')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Event Date')),
                ('time', models.TimeField(blank=True, default=datetime.time(6, 16, 52, 269395), verbose_name='Time')),
                ('ticker', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ticker')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entry Price')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stop Loss')),
                ('locate_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Locate Fees')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exit Price')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Commission')),
                ('trade_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Trade Type')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Screenshot')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('page_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.profile')),
            ],
        ),
    ]
