# Generated by Django 4.0.6 on 2022-07-25 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(6, 19, 20, 126099), verbose_name='Time'),
        ),
    ]
