# Generated by Django 4.0.6 on 2022-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='a',
            name='date',
        ),
        migrations.RemoveField(
            model_name='a',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='a',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='a',
            name='locate_fees',
        ),
        migrations.RemoveField(
            model_name='a',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='a',
            name='text',
        ),
        migrations.RemoveField(
            model_name='a',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='a',
            name='time',
        ),
        migrations.RemoveField(
            model_name='a',
            name='trade_type',
        ),
    ]
