# Generated by Django 4.0.6 on 2022-07-28 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='num_shares',
            field=models.IntegerField(default=0, max_length=10, verbose_name='Number of Shares'),
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(16, 11, 52, 218640), verbose_name='Time'),
        ),
    ]
