# Generated by Django 4.0.6 on 2022-07-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_a_commission_remove_a_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
