# Generated by Django 4.0.6 on 2022-07-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_trade_num_shares_trade_take_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='locate_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Locate Fees'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='num_shares',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=10, null=True, verbose_name='Number of Shares'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(16, 16, 25, 611869), verbose_name='Time'),
        ),
    ]
