# Generated by Django 4.0.6 on 2022-07-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_trade_trade_type_pageuser_trade_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='page_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.pageuser'),
        ),
    ]
