# Generated by Django 4.0.6 on 2022-07-24 05:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_trade_page_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageUser',
            new_name='Profile',
        ),
    ]
