# Generated by Django 4.0.6 on 2022-07-28 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_trade_commission_alter_trade_locate_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(16, 33, 34, 205831), verbose_name='Time'),
        ),
    ]
