# Generated by Django 4.0.6 on 2022-07-24 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 24, 21, 24, 48, 306329), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=1658697888.3063538, verbose_name='Time'),
        ),
    ]
