# Generated by Django 4.0.6 on 2022-07-24 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_trade_date_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 24), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(21, 29, 15, 281744), verbose_name='Time'),
        ),
    ]
