# Generated by Django 4.0.6 on 2022-07-24 22:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_trade_date_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(default=datetime.time(22, 32, 17, 308990), verbose_name='Time'),
        ),
    ]
