# Generated by Django 4.0.6 on 2022-07-24 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_trade_date_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(default=datetime.time(22, 32, 20, 715775), verbose_name='Time'),
        ),
    ]
