# Generated by Django 4.0.6 on 2022-07-24 22:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(22, 40, 56, 736933), verbose_name='Time'),
        ),
    ]
