# Generated by Django 4.0.6 on 2022-07-24 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_trade_page_user_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(22, 55, 50, 82257), verbose_name='Time'),
        ),
    ]
