# Generated by Django 4.0.6 on 2022-07-24 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='equity_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Equity at Time'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='page_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.profile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(23, 10, 36, 52377), verbose_name='Time'),
        ),
    ]
