# Generated by Django 4.0.6 on 2022-07-24 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_trade_page_user_alter_trade_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(23, 13, 18, 466865), verbose_name='Time'),
        ),
    ]
