# Generated by Django 4.0.6 on 2022-07-24 23:46

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_trade_page_user_alter_trade_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trade',
            managers=[
                ('current_trade', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(23, 46, 9, 297760), verbose_name='Time'),
        ),
    ]
